# Convertir datos y graficar

In [30]:
import mysql.connector
import pandas as pd
from datetime import datetime, timedelta

db = mysql.connector.connect(host="192.168.0.12",    #  host
                     user="operario",         #  usuario
                     passwd="",  #  password
                     db="dbp8100")        #  nombre de la base de datos

cur = db.cursor()

In [31]:
fecha_actual = datetime.now()
fecha_ayer = fecha_actual - timedelta(days=1)
fecha_actual = fecha_actual.strftime("%Y-%m-%d")
fecha_ayer = fecha_ayer.strftime("%Y-%m-%d")

fecha_actual = '2025-10-22'
fecha_ayer = '2025-05-01'
print(fecha_actual)
print(fecha_ayer)

2025-10-22
2025-05-01

In [32]:
# Extraer datos y convertir a df

# Datos mysql
cur.execute('''
            SELECT                 
                tareaseje.NroID,
                tareaseje.Fecha AS Fecha,
                tareaseje.Hora AS Hora,
                formulas.NroID AS IDF,
                formulas.Codigo AS Codigo,
                formulas.Nombre AS Nombre,
                tareaseje.Set AS Programado,
                (SELECT SUM(dcaptura.Valor) FROM dbp8100.dcaptura WHERE dcaptura.IDT = tareaseje.NroID) AS Dosificado,
                tareaseje.Tiempo AS Tiempo
            FROM 
                dbp8100.tareaseje AS tareaseje
            JOIN 
                dbp8100.formulas AS formulas ON formulas.NroID = tareaseje.IDF
            WHERE
                (tareaseje.Fecha = %s AND tareaseje.Hora >= '23:00:00') OR 
                (tareaseje.Fecha > %s AND tareaseje.Fecha <= %s)
            GROUP BY
                tareaseje.NroID
            ''',(fecha_ayer, fecha_ayer, fecha_actual),)
resultados = cur.fetchall()
# Obtener los nombres de las columnas
columnas = [desc[0] for desc in cur.description]

# Crear un DataFrame de pandas
df = pd.DataFrame(resultados, columns=columnas)

# Cerrar el cursor y la conexión
cur.close()
db.close()

# Mostrar el DataFrame
print(df)

      NroID       Fecha            Hora   IDF     Codigo  \
0     25798  2025-05-01 0 days 23:12:23  1204     08-066
1     25799  2025-05-02 0 days 01:55:58  1264  FP0030-01
2     25800  2025-05-02 0 days 07:11:22  1264  FP0030-01
3     25801  2025-05-02 0 days 08:30:05  1120     05-113
4     25802  2025-05-02 0 days 08:56:10  1120     05-113
...     ...         ...             ...   ...        ...
1517  27315  2025-10-22 0 days 03:27:11  1254     09-141
1518  27316  2025-10-22 0 days 09:05:00  1254     09-141
1519  27317  2025-10-22 0 days 12:45:54   369     07-017
1520  27318  2025-10-22 0 days 16:01:36  1120     05-113
1521  27319  2025-10-22 0 days 23:08:28  1244    R14-001

                                       Nombre  Programado  Dosificado  \
0                   INICIADOR MELAZA 14% A.A.     18000.0    18159.25
1                          TERNEROS  (Gepsa).     35000.0    26164.00
2                          TERNEROS  (Gepsa).     10000.0    10120.20
3                  RECRIA 16  AL 15%  A.A....     38000.0      996.45
4                  RECRIA 16  AL 15%  A.A....     37000.0    37172.30
...                                       ...         ...         ...
1517        CRE. MELAZA 10% A.A. (Los Roanos)     28000.0     5063.95
1518        CRE. MELAZA 10% A.A. (Los Roanos)     23000.0    23225.40
1519  DESTETE PRECOZ MELAZA 10% A.A. EXPELLER     15000.0    15169.40
1520               RECRIA 16  AL 15%  A.A....     10000.0     5057.80
1521          RECRIA 14 CON MAIZ (quebradora)      5000.0     5008.70

              Tiempo
0    0 days 02:37:13
1    0 days 05:11:55
2    0 days 01:15:10
3    0 days 00:25:51
4    0 days 07:42:52
...              ...
1517 0 days 05:37:02
1518 0 days 03:35:54
1519 0 days 03:05:26
1520 0 days 00:00:00
1521 0 days 00:44:32

[1522 rows x 9 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1522 entries, 0 to 1521
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   NroID       1522 non-null   int64
 1   Fecha       1522 non-null   object
 2   Hora        1522 non-null   timedelta64[ns]
 3   IDF         1522 non-null   int64
 4   Nombre      1522 non-null   object
 5   Programado  1522 non-null   float64
 6   Dosificado  1414 non-null   float64
 7   Tiempo      1522 non-null   timedelta64[ns]
dtypes: float64(2), int64(2), object(2), timedelta64[ns](2)
memory usage: 95.3+ KB

In [5]:
ultima_hora = df.loc[df.index[-1], 'Tiempo']
print(ultima_hora)

0 days 00:33:24

In [6]:
pd.isna(ultima_hora)

False

In [22]:
hora_actual = pd.to_timedelta(datetime.now().strftime('%H:%M:%S'))
print(hora_actual)

0 days 07:13:52

In [17]:
df

,NroID,Fecha,Hora,IDF,Nombre,Programado,Dosificado,Tiempo
0,25798,2025-05-01,0 days 23:12:23,1204,INICIADOR MELAZA 14% A.A.,18000.0,18159.25,0 days 02:37:13
1,25799,2025-05-02,0 days 01:55:58,1264,TERNEROS (Gepsa).,35000.0,26164.00,0 days 05:11:55
2,25800,2025-05-02,0 days 07:11:22,1264,TERNEROS (Gepsa).,10000.0,10120.20,0 days 01:15:10
3,25801,2025-05-02,0 days 08:30:05,1120,RECRIA 16 AL 15% A.A....,38000.0,996.45,0 days 00:25:51
4,25802,2025-05-02,0 days 08:56:10,1120,RECRIA 16 AL 15% A.A....,37000.0,37172.30,0 days 07:42:52
...,...,...,...,...,...,...,...,...
1517,27315,2025-10-22,0 days 03:27:11,1254,CRE. MELAZA 10% A.A. (Los Roanos),28000.0,5063.95,0 days 05:37:02
1518,27316,2025-10-22,0 days 09:05:00,1254,CRE. MELAZA 10% A.A. (Los Roanos),23000.0,23225.40,0 days 03:35:54
1519,27317,2025-10-22,0 days 12:45:54,369,DESTETE PRECOZ MELAZA 10% A.A. EXPELLER,15000.0,15169.40,0 days 03:05:26
1520,27318,2025-10-22,0 days 16:01:36,1120,RECRIA 16 AL 15% A.A....,10000.0,5057.80,0 days 00:00:00
1521,27319,2025-10-22,0 days 23:08:28,1244,RECRIA 14 CON MAIZ (quebradora),5000.0,5008.70,0 days 00:44:32

In [32]:
valor = df.loc[df.index[-1], 'Tiempo']
print(valor)
if valor == pd.Timedelta(seconds=0):
    print('Es cero')
else:
    print('Que paso')

0 days 00:00:00
Es cero

In [10]:
#Corregir los tiempos 0
# Identificar filas con tiempo 0
mask = df['Tiempo'] == pd.Timedelta(0)

# Calcular la diferencia de hora con la siguiente fila
df.loc[mask, 'Tiempo'] = df['Hora'].shift(-1) - df.loc[mask, 'Hora']

# Para la última fila, calcular diferencia con la hora actual
df.loc[df.index[-1], 'Tiempo'] = hora_actual - df.loc[df.index[-1], 'Hora']

df

,NroID,Fecha,Hora,IDF,Nombre,Programado,Dosificado,Tiempo
0,25183,2025-02-11,0 days 03:03:57,1244,RECRIA 14 SIN PELETEAR (quebradora),14000.0,14019.60,0 days 02:03:17
1,25184,2025-02-11,0 days 05:16:43,52,EQUINO SERVICIO,10000.0,10069.75,0 days 01:11:41
2,25185,2025-02-11,0 days 06:34:07,1120,RECRIA 16 AL 15% A.A....,22000.0,3012.10,0 days 00:39:20

In [33]:
df['Rendimiento'] = (df['Dosificado'] / (df['Tiempo'].astype('int64')/3.6e12))/1000
# df.dropna(inplace=True)
df

,NroID,Fecha,Hora,IDF,Codigo,Nombre,Programado,Dosificado,Tiempo,Rendimiento
0,25798,2025-05-01,0 days 23:12:23,1204,08-066,INICIADOR MELAZA 14% A.A.,18000.0,18159.25,0 days 02:37:13,6.930277
1,25799,2025-05-02,0 days 01:55:58,1264,FP0030-01,TERNEROS (Gepsa).,35000.0,26164.00,0 days 05:11:55,5.032883
2,25800,2025-05-02,0 days 07:11:22,1264,FP0030-01,TERNEROS (Gepsa).,10000.0,10120.20,0 days 01:15:10,8.078208
3,25801,2025-05-02,0 days 08:30:05,1120,05-113,RECRIA 16 AL 15% A.A....,38000.0,996.45,0 days 00:25:51,2.312843
4,25802,2025-05-02,0 days 08:56:10,1120,05-113,RECRIA 16 AL 15% A.A....,37000.0,37172.30,0 days 07:42:52,4.818532
...,...,...,...,...,...,...,...,...,...,...
1517,27315,2025-10-22,0 days 03:27:11,1254,09-141,CRE. MELAZA 10% A.A. (Los Roanos),28000.0,5063.95,0 days 05:37:02,0.901504
1518,27316,2025-10-22,0 days 09:05:00,1254,09-141,CRE. MELAZA 10% A.A. (Los Roanos),23000.0,23225.40,0 days 03:35:54,6.454488
1519,27317,2025-10-22,0 days 12:45:54,369,07-017,DESTETE PRECOZ MELAZA 10% A.A. EXPELLER,15000.0,15169.40,0 days 03:05:26,4.908308
1520,27318,2025-10-22,0 days 16:01:36,1120,05-113,RECRIA 16 AL 15% A.A....,10000.0,5057.80,0 days 00:00:00,inf
1521,27319,2025-10-22,0 days 23:08:28,1244,R14-001,RECRIA 14 CON MAIZ (quebradora),5000.0,5008.70,0 days 00:44:32,6.748249

In [ ]:
# #Filtrar por producto
# mask = df['Nombre'] == 'RECRIA 14 CON MAIZ (quebradora)'
# df_filtrado = df[mask]
# df_filtrado.info()
# df_filtrado

<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, 56 to 1521
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   NroID        70 non-null     int64
 1   Fecha        70 non-null     object
 2   Hora         70 non-null     timedelta64[ns]
 3   IDF          70 non-null     int64
 4   Codigo       70 non-null     object
 5   Nombre       70 non-null     object
 6   Programado   70 non-null     float64
 7   Dosificado   66 non-null     float64
 8   Tiempo       70 non-null     timedelta64[ns]
 9   Rendimiento  66 non-null     float64
dtypes: float64(3), int64(2), object(3), timedelta64[ns](2)
memory usage: 6.0+ KB

,NroID,Fecha,Hora,IDF,Codigo,Nombre,Programado,Dosificado,Tiempo,Rendimiento
56,25854,2025-05-08,0 days 23:11:10,1244,R14-001,RECRIA 14 CON MAIZ (quebradora),37000.0,32998.4,0 days 05:11:16,6.360797
57,25855,2025-05-09,0 days 04:22:46,1244,R14-001,RECRIA 14 CON MAIZ (quebradora),4000.0,4014.8,0 days 01:00:02,4.012571
58,25856,2025-05-09,0 days 05:23:07,1244,R14-001,RECRIA 14 CON MAIZ (quebradora),15000.0,4008.9,0 days 00:40:36,5.924483
59,25857,2025-05-09,0 days 06:04:13,1244,R14-001,RECRIA 14 CON MAIZ (quebradora),11000.0,11009.6,0 days 01:37:48,6.754356
85,25883,2025-05-13,0 days 09:34:05,1244,R14-001,RECRIA 14 CON MAIZ (quebradora),15000.0,NaN,0 days 00:00:16,NaN
...,...,...,...,...,...,...,...,...,...,...
1489,27287,2025-10-19,0 days 23:08:33,1244,R14-001,RECRIA 14 CON MAIZ (quebradora),9000.0,2995.6,0 days 01:28:55,2.021398
1490,27288,2025-10-20,0 days 00:38:00,1244,R14-001,RECRIA 14 CON MAIZ (quebradora),6000.0,6011.8,0 days 00:43:54,8.216583
1500,27298,2025-10-20,0 days 23:06:14,1244,R14-001,RECRIA 14 CON MAIZ (quebradora),4000.0,3998.6,0 days 00:21:41,11.064535
1514,27312,2025-10-22,0 days 00:52:50,1244,R14-001,RECRIA 14 CON MAIZ (quebradora),10000.0,6002.8,0 days 00:52:34,6.851642
1521,27319,2025-10-22,0 days 23:08:28,1244,R14-001,RECRIA 14 CON MAIZ (quebradora),5000.0,5008.7,0 days 00:44:32,6.748249

In [ ]:
# df_filtrado.to_csv('resumenR14.csv')

## Gráficos

In [12]:
import plotly.express as px

In [13]:
nombre = (df.index + 1).astype(str) + " - " + df['Nombre']

# Crear gráfico de barras
fig = px.bar(df, x=nombre, y='Dosificado', title='Producción por Producto')

# Mostrar el gráfico
fig.show()

In [14]:
hora = df['Hora'].astype('int64')/3.6e12
# Crear gráfico de barras
fig = px.line(df, x=hora, y='Rendimiento', title='Rendimiento por Producto')

# Mostrar el gráfico
fig.show()

### Etiquetas superiores

In [15]:
#Toneladas elaboradas
tn_total = df['Dosificado'].sum()

print(tn_total)

27101.449999999997

In [16]:
# Horas totales
hs_total = df['Tiempo'].astype('int64').sum() / 3.6e12

print(hs_total)

3.905

In [17]:
#Rendimiento promedio
rendimiento_gral = (tn_total / hs_total)/1000
print(rendimiento_gral)

6.940192061459666

In [18]:
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Indicator(
    value = 200,
    delta = {'reference': 160},
    gauge = {
        'axis': {'visible': False}},
    domain = {'row': 0, 'column': 0}))

fig.add_trace(go.Indicator(
    value = 120,
    gauge = {
        'shape': "bullet",
        'axis' : {'visible': False}},
    domain = {'x': [0.05, 0.5], 'y': [0.15, 0.35]}))

fig.add_trace(go.Indicator(
    mode = "number+delta",
    value = 300,
    domain = {'row': 0, 'column': 1}))

fig.add_trace(go.Indicator(
    mode = "delta",
    value = 40,
    domain = {'row': 1, 'column': 1}))

fig.update_layout(
    grid = {'rows': 2, 'columns': 2, 'pattern': "independent"},
    template = {'data' : {'indicator': [{
        'title': {'text': "Speed"},
        'mode' : "number+delta+gauge",
        'delta' : {'reference': 90}}]
                         }})